### PR TITLE
adding badges

### PR DESCRIPTION
**Pull request by brozeph**
We'll need to get coverage up - I haven't looked closely, but perhaps it's a weird issue with how coveralls interprets the reports. 

Additionally, note the missing dependencies that were required to get the build to work properly. These little details are killers (<https://travis-ci.org/PlayNetwork/fs-promise-util/jobs/231622328#L420>).

### CODE REVIEW

**Comment by sanakanchha** [comment]
@brozeph yeah, looks like the report interpretation is different with coveralls since the coverage is above 80% while running the tests.

**Comment by sanakanchha** [comment]
Also, the build is failing as it is pointing to master and there is no code to build in master.
Build Status

Just to test, I changed the branch to v1.0.1 and that passes the build.
[Build Status]

Hence, once v1.0.1 is merged to master, build passes.

**Comment by sanakanchha** [comment]
Looking into why the coveralls reports less % code coverage. Also will look into bumping up the coverage.

**Comment by sanakanchha** [comment]
@brozeph added test that bumped code coverage above 90%
[Build Status](https://travis-ci.org/PlayNetwork/fs-promise-util)[Coverage Status](https://coveralls.io/github/PlayNetwork/fs-promise-util?branch=v1.0.1)

**Review by rmomii — APPROVED** [review]

**Pull request merged**
